disabled_rules:
  - trailing_whitespace
  - identifier_name
  - nesting
  - force_cast
  - force_try
  - inclusive_language
  - type_name
  - multiple_closures_with_trailing_closure
  - trailing_comma # it is more consistent to have a comma on every line

analyzer_rules:
  - capture_variable

opt_in_rules:
  - attributes
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - generic_type_name
  - implicit_return
  - inclusive_language
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - modifier_order
  - toggle_bool
  #- file_name
  #- file_name_no_space
  #- array_init
  #- closure_body_length # Apply this one
  #- conditional_returns_on_newline # I don't like this rule
  #- discouraged_optional_collection # I'm not sure if this is useful, as a nil collection can have a meaning.
  #- empty_xctest_method # this conflicts with the `balanced_xctest_lifecycle` rule
  #- explicit_acl # this is an interesting rule but perhaps a bit overkill.
  #- explicit_enum_raw_value # string enums are fine having their names as values. Also just supplying the first value in a int enum is fine.
  #- explicit_self # I don't agree.
  #- explicit_top_level_acl # this would be good, but is a big job. !!!!!!!!!!!!!!!!!!!!!!!!!!!
  #- explicit_type_interface # I don't agree.
  #- extension_access_modifier # Don't understand this one. Take another look when you have time.
  #- file_types_order # Would be worthwile, but is quite a bit of work to tidy up. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #- force_unwrapping # Good but big job. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #- function_default_parameter_at_end # not sure about this.
  #- ibinspectable_in_extension # kind of makes sense
  #- identical_operands # Good
  #- implicitly_unwrapped_optional # good idea!!!!!!!!!!!!!!!!!!
  #- indentation_width # no
  #- legacy_objc_type # Good
  #- let_var_whitespace # Good, but buggy
  #- literal_expression_end_indentation # No. Too restrictive.
  #- lower_acl_than_parent # Worth looking into.
  #- missing_docs # no
  #- multiline_arguments # nöö. Not always good.
  

excluded:
  - CodeGeneration
  - MockServer/Derived
  - OurFrameworks/Networking/CodeGeneration
  - OurFrameworks/Networking/Source/Networking2/API/AnyEncodable.swift
  - Tests/CodeGeneration
  - Tests/Mocks
  - ../fastlane
  - ../IntellumSocial/ScreenshotUITests/Helpers/SnapshotHelper.swift
  - ../Pods

line_length: 150

type_body_length:
  - 300 # warning
  - 600 # error

cyclomatic_complexity: # lower this from time to time until we get to 5 which is what codeclimate is set to.
  warning: 8
  error: 9
  ignores_case_statements: true

file_length:
  warning: 600
  error: 700
